### PR TITLE
Add myself as a contributor

### PR DESCRIPTION
**Pull request by wu-sheng**
@bensigelman , I have add myself on the contributors page.

### CODE REVIEW

**Comment by bensigelman** [comment]
@wu-sheng the actual change looks good... can you perhaps squash these commits down in `git`? (There are a bunch of commits that don't pertain to the PR here)

**Comment by yurishkuro** [comment]
@bensigelman squashing can be done during the merge

image

We could change the repo setting to disallow full merge altogether, but for some reason right now GitHub doesn't let me change it

image

**Comment by wu-sheng** [comment]
I will send a new RP instead. @bensigelman , please check what @yurishkuro mentioned.

**Comment by wu-sheng** [comment]
Already send #160.

**Pull request closed without merging**
