### PR TITLE
add php traceing molten

### PR DESCRIPTION
**Pull request by silkcutKs**
add php traceing molten

### CODE REVIEW

**Comment by silkcutKs** [comment]
if the molten provide an interactive APIs in php moldule,  can it join the opentracing?

**Comment by wu-sheng** [comment]
@silkcutKs I think the most important thing is, we must work with all @opentracing/otsc and @opentracing/otiab members, always other people have interested about php-lib. And provide the official **PHP** lib, then you can do as an implementation.

**Comment by wu-sheng** [comment]
Thanks to @tedsuo for adding PHP-lib on the website. @silkcutKs , you should follow this repository: https://github.com/opentracing/opentracing-php, and provide the implementation. :)

**Comment by tedsuo** [comment]
Hi @silkcutKs, just following up on this. Is Molten opentracing compliant? If so I'm happy to add it.

**Comment by wu-sheng** [comment]
Molten is auto instrument, no open APIs, and last time I checked, no bridge provided.

**Comment by tedsuo** [comment]
@silkcutKs  I'm going to close this for now, feel free to reopen.

**Pull request closed without merging**
