### PR TITLE
Add new supported tracer

### PR DESCRIPTION
**Pull request by wu-sheng**
Add ‘skywalking’ on supported tracer list.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@bensigelman screenshot:

wx20170123-161036

**Comment by wu-sheng** [comment]
I think I miss updating some introductions on document page about supported tracers.

Add it tomorrow.

**Comment by wu-sheng** [comment]
@bensigelman @yurishkuro , I think this PR is ready.

**Comment by bensigelman** [comment]
LGTM, thanks!

**Pull request merged**
