### PR TITLE
Add sharding-jdbc as supported framework.

### PR DESCRIPTION
**Pull request by wu-sheng**
Sharding-JDBC is a JDBC extension. Sharding is a common way in China, when too much data for a single MySQL, but NoSQL or some other newSQL Database, because of Ops-concern or traditional Transaction requirements. It support to route(sometimes change) sql to different MySQL instances(or table) by hash, range or other rules, according to analysis result of SQL statement at run time.

I worked with their team on this, and tested by using SkyWalking OpenTracing Bridge with [sharding-jdbc-opentracing](https://github.com/shardingjdbc/sharding-jdbc-opentracing)

Thanks for @hanahmily @terrymanu .

### CODE REVIEW

**Comment by yurishkuro** [comment]
could you post a screenshot how it looks in the UI?

**Comment by wu-sheng** [comment]
It looks like this:

image

**Comment by wu-sheng** [comment]
And the CI error is:
```
ERROR:  Error installing jekyll:
	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
```

I assume It is not triggered by my chances, right?

**Comment by yurishkuro** [comment]
Thanks. 

The error is not sure to your changes, but your changes may not make it to the website because of it, so we should fix it first. Looks like a dependency got stale, but I'm not seeing where is defined.

**Comment by wu-sheng** [comment]
@reimertz Maybe you can help us on this, please.

**Comment by wu-sheng** [comment]
@tedsuo @bhs @yurishkuro Anyone can help me on this CI issue? Seems I am being blocked.

**Comment by tedsuo** [comment]
@wu-sheng let me know if a rebase does not solve this.

**Pull request merged**
