### PR TITLE
Use Hugo's assets pipeline

### PR DESCRIPTION
**Pull request by lucperkins**
Hugo has a new feature that enables you to process JavaScript and Sass with it rather than requiring an external pipeline.

**NOTE**: The version of Hugo with this feature is not yet available on Netlify. Don't merge this until I verify that it's available.

### CODE REVIEW

**Comment by tedsuo** [comment]
Ooooh, do I understand this to mean we can drop nodejs as a dependency?

**Comment by lucperkins** [comment]
@tedsuo Yep! Just the Hugo binary and that’s it.

**Comment by lucperkins** [comment]
@tedsuo I was having issues getting this to work on Netlify but I figured it out. So I'm gonna go ahead and merge this for now 👍

**Comment by lucperkins** [comment]
@tedsuo Hmmm. I'm incredibly confused. I merged this and now these changes don't show up in the `v2.0` branch. I'm currently investigating but I can't say I've encountered anything like this before.

**Pull request merged**
