### PR TITLE
Updated OTOV_3.png

### LINKED ISSUE #231: Typo in OTOV_3.png: 'stoage' -> 'storage'
I cannot find the sources to fix that, but there is a typo in documentation/images/OTOV_3.png: instead of 'storage allocation' it says 'stoAge allocation'.

### PR DESCRIPTION
**Pull request by AarshiyaGuneja**
Fixes #231

### CODE REVIEW

**Comment by yurishkuro** [comment]
what is the source of this png? any chance we can store the original, not just the rendered version?

also, the new image seems to be large, is that going to mess up the site layout?

**Comment by AarshiyaGuneja** [comment]
I have made this image myself using Lucidchart.

**Comment by AarshiyaGuneja** [comment]
I have resized the image as original so that it doesn't create any issues further.

**Comment by yurishkuro** [comment]
is it possible to expose the original source of the image from lucidchart? I case we need to change it in the future would be nice to have the vector based original.

**Comment by AarshiyaGuneja** [comment]
Yes, it can be done. 
I have made the changes to the original image as well. I'm attaching the image here. If it seems appropriate to you, I'll commit the changes.
otov_3

**Comment by yurishkuro** [comment]
> I have made the changes to the original image as well. I'm attaching the image here.

To clarify, did you work on the actual rendered image, or some vector objects (like shapes in google docs)? My question was about the latter, since you mentioned lucidcharts.

**Comment by AarshiyaGuneja** [comment]
I have used some shapes to design the image as original in Lucidchart.

**Pull request merged**
