### PR TITLE
Add a registry of tracers, plugins, and instrumentation to the website.

### PR DESCRIPTION
**Pull request by austinlparker**
This PR adds a new feature to the website, a searchable registry. This is intended as the soft launch of this feature - we'll need the community to flesh out the existing auto-generated stubs that I created by scraping contrib.

(closes #348)

### CODE REVIEW

**Comment by austinlparker** [comment]
I put this in front of a designer for feedback and want to address some of their notes before we merge, so please hold off on merging. Feel free to review/submit comments at your leisure!

**Comment by yurishkuro** [comment]
I tried the preview, but wasn't able to get the search working. Is it supposed to be interactive?

**Comment by austinlparker** [comment]
You have to hit enter after you type something in. I'm trying to make that more clear.

**Comment by yurishkuro** [comment]
minor suggestion:
  * rename lightstep files to start with language, to match the rest of the files
  * make the sort on the main registry page case-insensitive

**Pull request merged**
