### PR TITLE
Featured Medium post should be most recent post

### PR DESCRIPTION
**Pull request by austinlparker**
This adds some dynamic fetching of the Medium RSS feed in order to display the most recent post on the frontpage rather than using the site data supplied URL.

### CODE REVIEW

**Comment by tedsuo** [comment]
Some thoughts:
* I'd prefer this to be a server-side feature, and to generally eliminate JS from the the site. 
* I don't think we should hold up rendering of the page on the client-side to wait for this query, but I do think this approach will create viewing issues, especially on slow/mobile connections. 
* However, as a `v1` I think this is totally fine.

**Comment by yurishkuro** [comment]
My vote is for dynamic non-blocking pull via JS (we did the same on https://www.jaegertracing.io/).  I don't want to redeploy the site then posts are added to Medium.

**Comment by lucperkins** [comment]
One possibility worth exploring is rebuilding the site via webhook. We could set up a simple [IFTTT}(https://ifttt.com/discover) applet that `POST`s to a [Netlify webhook](https://www.netlify.com/docs/webhooks/) that rebuilds the site.

In terms of presenting a list of posts statically, Hugo has a convenient `getJSON` function that can pull in post metadata from Medium. containerd's [downloads page](https://containerd.io/downloads/), for example, uses `getJSON` to get release info from the GitHub API.

I've added a webhook in Netlify. The only remaining step would be setting up the IFTTT applet, which I lack permissions to do.

**Comment by iredelmeier** [comment]
I like @lucperkins's idea 👍

**Comment by austinlparker** [comment]
I like the IFTTT idea, are we OK merging with this in its current state to get updates going then I'll work the IFTTT idea?

**Comment by lucperkins** [comment]
@austinlparker Yeah, I think best to merge this now. I can re-work the setup to use Hugo to fetch the JSON from the Medium API. The one missing piece would be to set up the IFTTT pipeline, which can only be done by an "owner" of the Medium blog (which I'm not). I've already set up the Netlify webhook. Do you have access to the Netlify dashboard? If not I can email you the private URL for the HTTP endpoint.

**Comment by austinlparker** [comment]
@lucperkins I've got access to Netlify, yeah. I'll look into getting the IFTTT stuff set up. Thanks!

**Pull request merged**
