### PR TITLE
Added Outreachy landing page

### PR DESCRIPTION
**Pull request by jpkrohling**
The landing page requirements for the Outreachy program are located here: https://www.outreachy.org/mentor/landing-page-requirements/

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
I'd like to add a page with this content to OpenTracing's website, but I couldn't get it to work with the website's design and I need some help :)

Could someone look into this and see what I'd need to do, to make it look good?

**Comment by pritianka** [comment]
Thanks for this, Juraci!

Hi @reimertz - can you please take a look and help out.
ᐧ

Priyanka Sharma
Advisor, HeavyBit <http://heavybit.com/>
Head of Marketing & Partnerships, LightStep <http://lightstep.com/>
Co-founder, WakaTime <http://www.wakatime.com/> - Quantify your coding
www.twitter.com/pritianka
650-796-7125

*I'm speaking at OSCON | May 8-11, 2017 http://oreil.ly/2jboNPo
<http://oreil.ly/2jboNPo> #OSCON*

**Comment by jpkrohling** [comment]
This page should follow the landing page requirements, but for the record, here are they: 
https://www.outreachy.org/mentor/landing-page-requirements/

**Comment by reimertz** [comment]
Hi @jpkrohling! 👋

In order to be able to help out, I first need to know how this should be surfaced. 

- Is going to be a one of ting, meaning that it should be a separate page you'll link to?
- do we want to add it to the landing page?

We could apply both, adding a temporary button the landing page, linking to the page. 

Once we sort this out, I can, if you don't mind, migrate your current PR so it works with the current setup. 

cc @bhs @pritianka

**Comment by jpkrohling** [comment]
> Once we sort this out, I can, if you don't mind, migrate your current PR so it works with the current setup.

I don't mind at all :) At this moment, it could be a single page and it would be awesome to have it linked from the main page and perhaps have it listed on the nav bar somewhere.

**Comment by jpkrohling** [comment]
This is now ready to be merged. Thanks @reimertz !

**Comment by objectiser** [comment]
@reimertz Thanks for your help on this. Would it be possible to get the PR merged today, and do any necessary tweaks in separate PRs, as the Outreachy organizers need a landing page for the project asap?

**Pull request merged**
